{{- if .Values.kubeOidcProxy.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    description: kube-oidc-proxy-ingress
    displayName: kube-oidc-proxy-ingress
    httpSend: /
    ingress-lb: {{ .Values.ingress.name }}
    kubernetes.io/ingress.class: {{ .Values.ingress.name }}
    nginx.ingress.kubernetes.io/enable-access-log: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "false"
    nginx.ingress.kubernetes.io/load-balance: round_robin
    nginx.ingress.kubernetes.io/proxy-body-size: ""
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/server-alias: ""
    nginx.ingress.kubernetes.io/upstream-vhost: $host
  labels:
    ingress-lb: {{ .Values.ingress.name }}
  name: kube-oidc-proxy-server-ingress
  namespace: {{ .Release.Namespace }}
spec:
#  ingressClassName: {{ .Values.ingress.name }}
  rules:
  - host: {{ .Values.kubeOidcProxy.host }}
    http:
      paths:
      - backend:
          service:
            name: kube-oidc-proxy-server
            port:
              number: 8022
        path: /
        pathType: ImplementationSpecific
{{- end }}