{{- if .Values.ldapProvider.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-storage
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.ldapProvider.storageClass }}
{{- end }}
